### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by BloodEvolution** [F9mc/Bot-Feur#2]
https://www.rfc-editor.org/rfc/rfc-index.txt

**Comment by Efrei-Paul** [comment]
D'accord @BloodEvolution, peux tu préciser la RFC s'il te plait ?

**Comment by BloodEvolution** [comment]
All of it

**Comment by Efrei-Paul** [comment]
Non thanks

**Comment by Efrei-Paul** [comment]
@BloodEvolution la clause 7.4 de l'ISO27001, tu en penses quoi ?

**Comment by Efrei-Paul** [comment]
TODO RFC 2119
